sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose build
script:
  - docker build . -t $APP_IMAGE
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
